# Generated by Django 3.1.5 on 2021-01-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210106_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmentation',
            name='escrito_b',
        ),
        migrations.RemoveField(
            model_name='segmentation',
            name='umenlance',
        ),
        migrations.RemoveField(
            model_name='segmentation',
            name='umescrito_a',
        ),
        migrations.RemoveField(
            model_name='segmentation',
            name='umimagen_a',
        ),
        migrations.RemoveField(
            model_name='segmentation',
            name='umlinea',
        ),
        migrations.RemoveField(
            model_name='segmentation',
            name='ummarco',
        ),
        migrations.RemoveField(
            model_name='segmentation',
            name='umotro',
        ),
        migrations.RemoveField(
            model_name='segmentation',
            name='umrealzado_a',
        ),
        migrations.AlterField(
            model_name='segmentation',
            name='area_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True),
        ),
    ]
