# Generated by Django 3.1.5 on 2021-01-06 18:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Segmentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(max_length=100)),
                ('document_name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=500)),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='upload/images/')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('area_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('condificados', models.IntegerField()),
                ('memos', models.IntegerField()),
                ('umescrito_a', models.BooleanField(default=False)),
                ('escrito_b', models.BooleanField(default=False)),
                ('umrealzado_a', models.BooleanField(default=False)),
                ('umenlance', models.BooleanField(default=False)),
                ('umimagen_a', models.BooleanField(default=False)),
                ('umlinea', models.BooleanField(default=False)),
                ('ummarco', models.BooleanField(default=False)),
                ('umotro', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
