# Generated by Django 3.1.5 on 2021-01-06 19:41

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentation',
            name='area_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='segmentation',
            name='image',
            field=models.ImageField(upload_to=app.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='segmentation',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
