# Generated by Django 3.1.6 on 2021-02-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210109_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentation',
            name='selected',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
