# Generated by Django 3.1.6 on 2021-02-21 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_segmentation_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmentation',
            name='color',
        ),
        migrations.RemoveField(
            model_name='segmentation',
            name='condificados',
        ),
        migrations.RemoveField(
            model_name='segmentation',
            name='memos',
        ),
        migrations.RemoveField(
            model_name='segmentation',
            name='percentage',
        ),
        migrations.AlterField(
            model_name='segmentation',
            name='end',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='segmentation',
            name='start',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
