# Generated by Django 3.1.7 on 2021-03-16 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210316_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpus',
            name='segmentation',
        ),
        migrations.AddField(
            model_name='segmentation',
            name='corpus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.corpus'),
        ),
    ]
