# Generated by Django 3.1.7 on 2021-03-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210316_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='corpus_document',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
