# Generated by Django 3.1.7 on 2021-03-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_corpus_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='gender',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
