# Generated by Django 3.1.7 on 2021-03-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210316_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='corpus_document',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
