# Generated by Django 3.1.7 on 2021-03-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210316_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpus',
            name='corpus_pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
